package filter

const (
	CondEquals             string = "equals"
	CondDoesNotEqual       string = "does_not_equal"
	CondGreaterThan        string = "greater_than"
	CondLessThan           string = "less_than"
	CondGreaterThanOrEqual string = "greater_than_or_equal_to"
	CondLessThanOrEqual    string = "less_than_or_equal_to"
	CondIsEmpty            string = "is_empty"
	CondIsNotEmpty         string = "is_not_empty"
	CondContains           string = "contains"
	CondDoesNotContain     string = "does_not_contain"
	CondStartsWith         string = "starts_with"
	CondEndsWith           string = "ends_with"
	CondBefore             string = "before"
	CondAfter              string = "after"
	CondOnOrBefore         string = "on_or_before"
	CondOnOrAfter          string = "on_or_after"
	CondPastWeek           string = "past_week"
	CondPastMonth          string = "past_month"
	CondPastYear           string = "past_year"
	CondNextWeek           string = "next_week"
	CondNextMonth          string = "next_month"
	CondNextYear           string = "next_year"
)
